-- CreateEnum
CREATE TYPE "Area" AS ENUM ('FIFTH_SETTLEMENT', 'FIRST_SETTLEMENT', 'THIRD_SETTLEMENT', 'REHAB', 'MADINATY', 'SHOROUK', 'BADR_CITY', 'EL_OBOUR', 'NASR_CITY', 'HELIOPOLIS', 'NOZHA', 'EL_TAGAMOA', 'EL_MARG', 'AIN_SHAMS', 'DOWNTOWN_CAIRO', 'GARDEN_CITY', 'ZAMALEK', 'MOHANDESSIN', 'DOKKI', 'AGOUZA', 'BULAQ', 'ABDEEN', 'SAYEDA_ZEINAB', 'EL_DAHER', 'SIXTH_OF_OCTOBER', 'SHEIKH_ZAYED', 'HARAM', 'FAISAL', 'IMBABA', 'WARRAQ', 'ROD_EL_FARAG', 'MAADI', 'NEW_MAADI', 'DEGLA', 'ZAHRAA_EL_MAADI', 'HELWAN', 'TORA', 'BASATEEN', 'DAR_EL_SALAM');

-- AlterTable
ALTER TABLE "Account" ADD COLUMN     "area" "Area" NOT NULL DEFAULT 'HELIOPOLIS';
